### ISSUE TITLE
np array to rasterio dataset

### ISSUE THREAD

**Issue by chipfranzen** [mapbox/rasterio-cookbook#4]
The outputs of functions like `warp.merge` and `mask.mask` are numpy arrays. Can you populate [this section](https://github.com/mapbox/rasterio-cookbook#creating-raster-from-numpy-array) of the cookbook? I'm often having to write temp files and reload them to convert np arrays to rasterio datasets.

Thanks.

**Comment by Guitlle** [comment]
I just had this issue. I have to make temporary raster files as well.

**Comment by bpstewar** [comment]
Just want to bump this, as I am encountering this problem as well

**Comment by sgillies** [comment]
Sorry, the author of that doc has moved on. I'm not sure what the intent was for that section. Temporary raster files, whether on disk or in memory, are the way to go.
